blank_issues_enabled: true
contact_links:
  - name: Proposer un module / Suggest a module
    url: https://github.com/starman-tech/yuzu-modules/issues
    about: Les modules communautaires ont leur propre dépôt.
